{"uuid":"03fd14b7-fe89-4baf-a9e6-2508e89df84c","historyId":"65bdc03cc92865185c418fa4ef40bdf9","fullName":"TestCase.CreateNewLeadFromCRM.leadAssignementToInfinity","labels":[{"name":"package","value":"TestCase.CreateNewLeadFromCRM"},{"name":"testClass","value":"TestCase.CreateNewLeadFromCRM"},{"name":"testMethod","value":"leadAssignementToInfinity"},{"name":"parentSuite","value":"Default suite"},{"name":"suite","value":"Default test"},{"name":"subSuite","value":"TestCase.CreateNewLeadFromCRM"},{"name":"host","value":"RADHA"},{"name":"thread","value":"3384@RADHA.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"story","value":"Lead Assignment from CRM to RO"},{"name":"feature","value":"Lead Creation and Assignment"},{"name":"epic","value":"Lead Management"},{"name":"severity","value":"critical"}],"links":[],"name":"Lead Assignment ","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"java.io.FileNotFoundException: src\\main\\java\\com\\qa\\testdata\\Infinity_Test_Data.xlsx (The process cannot access the file because it is being used by another process)","trace":"java.lang.RuntimeException: java.io.FileNotFoundException: src\\main\\java\\com\\qa\\testdata\\Infinity_Test_Data.xlsx (The process cannot access the file because it is being used by another process)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:58)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:159)\r\n\tat org.testng.internal.Parameters.handleParameters(Parameters.java:809)\r\n\tat org.testng.internal.Parameters.handleParameters(Parameters.java:734)\r\n\tat org.testng.internal.invokers.ParameterHandler.handleParameters(ParameterHandler.java:72)\r\n\tat org.testng.internal.invokers.ParameterHandler.createParameters(ParameterHandler.java:51)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:946)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1597)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:739)\r\n\tat org.testng.TestRunner.run(TestRunner.java:614)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:421)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:312)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1208)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1112)\r\n\tat org.testng.TestNG.run(TestNG.java:1079)\r\n\tat org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)\r\n\tat org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)\r\n\tat org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)\r\nCaused by: java.io.FileNotFoundException: src\\main\\java\\com\\qa\\testdata\\Infinity_Test_Data.xlsx (The process cannot access the file because it is being used by another process)\r\n\tat java.base/java.io.FileInputStream.open0(Native Method)\r\n\tat java.base/java.io.FileInputStream.open(FileInputStream.java:219)\r\n\tat java.base/java.io.FileInputStream.<init>(FileInputStream.java:159)\r\n\tat java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)\r\n\tat com.qa.util.excelUtils.getExcelData(excelUtils.java:17)\r\n\tat com.qa.util.qa_infinity_dataProviderutils.getLoginDetails(qa_infinity_dataProviderutils.java:15)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:54)\r\n\t... 25 more\r\n"},"stage":"finished","description":"Verify that a supervisor can create and Telecaller assign to infinity","steps":[],"attachments":[],"parameters":[],"start":1748951976215,"stop":1748951976222}